"""Add chat_id to Channel model

Revision ID: 47d079a86000
Revises: eda1aba9e9b1
Create Date: 2024-08-27 10:48:20.934729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d079a86000'
down_revision = 'eda1aba9e9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channel', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.alter_column('channel', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('channel', 'chat_id')
    op.drop_table('notification')
    # ### end Alembic commands ###
