"""Add chat_id to Channel model

Revision ID: b881173c1266
Revises: 47d079a86000
Create Date: 2024-08-27 10:57:23.029179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b881173c1266'
down_revision = '47d079a86000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaway', sa.Column('announced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaway', 'announced')
    # ### end Alembic commands ###
